# flake8: noqa

# In[]:
# Controls for webapp

FACULTY = dict(
    FAS="FAS",
    FBF="FBF",
    FEGT="FEGT",
    FICT="FICT",
    FSc="FSc",
    CFSKPR="CFSKPR",
    ICSKPR="ICSKPR",
    FAM="FAM",
    FMHS="FMHS",
    FCI="FCI",
    LKCFES="LKCFES",
    CFSSGL="CFSSGL",
    ICSSGL="ICSSGL",
)

DEPARTMENT = dict(
    DOA="DOA",
    DBPM="DBPM",
    DOE="DOE",
    DIB="DIB",
    DOAD="DOAD",
    DOJ="DOJ",
    DOLL="DOLL",
    DPAC="DPAC",
    DPR="DPR",
    DOB="DOB",
    DOCA="DOCA",
    DE="DE",
    DOEN="DOEN",
    DOF="DOF",
    DOM="DOM",
    DGS="DGS",
    DGEN="DGEN",
    DMC="DMC",
    DM="DM",
    DML='DML',
    DMDA="DMDA",
    DCM="DCM",
    DEE="DEE",
    DEV="DEV",
    DIE="DIE",
    DPCE="DPCE",
    DCMED="DCMED",
    DMED="DMED",
    DON="DON",
    DOP="DOP",
    DOPM="DOPM",
    DPCS="DPCS",
    DAFS="DAFS",
    DAHS="DAHS",
    DBS="DBS",
    DCHS="DCHS",
    DPMS="DPMS",
    DASD="DASD",
    DCE="DCE",
    DCEN="DCEN",
    DEEE="DEEE",
    DIECS="DIECS",
    DMAS="DMAS",
    DMME="DMME",
    DMBE="DMBE",
    DOS="DOS",
    DMA="DMA",
    DSEKPR="DSEKPR",
    DSESGL="DSESGL",
    DCS="DCS",
    DCCT="DCCT",
    DIS="DIS",
)

DEPARTMENT_COLORS = dict(
    DOA="#FFEDA0",
    DBPM="#FA9FB5",
    DOE="#A1D99B",
    DIB="#BFD3E6",
    DOAD="#B3DE69",
    DOJ="#FDBF6F",
    DOLL="#FC9272",
    DPAC="#D0D1E6",
    DPR="#ABD9E9",
    DOB="#3690C0",
    DOCA="#F87A72",
    DE="#CA6BCC",
    DOEN="#DD3497",
    DOF="#4EB3D3",
    DOM="#FFFF33",
    DGS="#FB9A99",
    DGEN="#A6D853",
    DMC="#D4B9DA",
    DM="#AEB0B8",
    DML="#CCCCCC",
    DMDA="#EAE5D9",
    DCM="#C29A84",
    DEE="#67BD65",
)
